<!-- Modernizer JS -->
<script src="{{ asset('assets/landing/js/vendor/modernizr.min.js') }}"></script>
<!-- jQuery JS -->
<script src="{{ asset('assets/landing/js/vendor/jquery.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/sal.min.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/backtotop.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/magnifypopup.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/slick.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/countdown.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/jquery-appear.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/odometer.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/isotop.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/imageloaded.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/lightbox.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/wow.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/paralax.min.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/paralax-scroll.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/jquery-ui.js') }}"></script>
<script src="{{ asset('assets/landing/js/vendor/tilt.jquery.min.js') }}"></script>
<!-- Main JS -->
<script src="{{ asset('assets/landing/js/main.js') }}"></script>